### ISSUE TITLE
Convert it into package

### ISSUE THREAD

**Issue by krishyadav007** [ryichando/veddy#2]
Hi, I urgently need this technique, 

Can you make it a python package, so that we can pass the XML file as a  parameter to the function from the package?

**Comment by ryichando** [comment]
Thank you for reaching out. Since Veddy heavily depends on an external program ffmpeg, it is not doable to encapsulate everything in a single python package. Instead, you may choose either from two options:

- Look into https://github.com/ryichando/veddy/blob/master/Dockerfile and set up your local environment. Run "python3 main.py" followed by your XML input parameter(s).

- Pass "--complex_filter" as an additional parameter. Veddy outputs a lengthy ffmpeg command line. For example,

`docker run -v $PWD:/veddy --rm veddy examples/concat.xml --complex_filter`

gives you

`ffmpeg -stats -y -i examples/videos/cat.mp4 -i examples/videos/dog.mp4 -filter_complex "color=color=black@1.0:s=480x270:d=1:r=25.0[color-0];[color-0]drawtext=text='Cat':fontsize=28.799999999999997:fontcolor=white:x=(w-text_w)/2+(0):y=(h-text_h)/2+(0)[drawtext-0];[0]fps=25.0[img-fps-0];color=color=black@1.0:s=480x270:d=1:r=25.0[color-1];[color-1]drawtext=text='Dog':fontsize=28.799999999999997:fontcolor=white:x=(w-text_w)/2+(0):y=(h-text_h)/2+(0)[drawtext-1];[1]fps=25.0[img-fps-1];[drawtext-0]split=3[split-0][split-1][split-2];[split-0]setpts=if(eq(N\,0)\,PTS-STARTPTS\,PTS-STARTPTS+(0/TB))[setpts-0];[setpts-0]fps=fps=25.0[fps-0];[fps-0]trim=start=0:end=0[trim-0];nullsrc=s=480x270:d=3.0:r=25.0[nullsrc-0];[nullsrc-0][split-2]overlay=x=0:y=0:shortest=0:format=auto[overlay-0];[overlay-0]trim=start=1.0:end=3.0[trim-1];[trim-1]setpts=PTS-STARTPTS[setpts-1];[trim-0][split-1][setpts-1]concat=n=3[concat-1];[concat-1]settb=0.04[settb-0];[img-fps-0]split=3[split-3][split-4][split-5];[split-3]setpts=if(eq(N\,0)\,PTS-STARTPTS\,PTS-STARTPTS+(2/TB))[setpts-2];[setpts-2]fps=fps=25.0[fps-1];[fps-1]trim=start=0:end=2[trim-2];nullsrc=s=480x270:d=5.0:r=25.0[nullsrc-1];[nullsrc-1][split-5]overlay=x=0:y=0:shortest=0:format=auto[overlay-1];[overlay-1]trim=start=5.0:end=5.0[trim-3];[trim-3]setpts=PTS-STARTPTS[setpts-3];[trim-2][split-4][setpts-3]concat=n=3[concat-2];[concat-2]settb=0.04[settb-1];[settb-0][settb-1]xfade=transition=fade:duration=1:offset=2.0[xfade-0];[xfade-0]split=3[split-6][split-7][split-8];[split-6]setpts=if(eq(N\,0)\,PTS-STARTPTS\,PTS-STARTPTS+(0/TB))[setpts-4];[setpts-4]fps=fps=25.0[fps-2];[fps-2]trim=start=0:end=0[trim-4];nullsrc=s=480x270:d=11.0:r=25.0[nullsrc-2];[nullsrc-2][split-8]overlay=x=0:y=0:shortest=0:format=auto[overlay-2];[overlay-2]trim=start=9.0:end=11.0[trim-5];[trim-5]setpts=PTS-STARTPTS[setpts-5];[trim-4][split-7][setpts-5]concat=n=3[concat-3];[concat-3]settb=0.04[settb-2];[drawtext-1]split=3[split-9][split-10][split-11];[split-9]setpts=if(eq(N\,0)\,PTS-STARTPTS\,PTS-STARTPTS+(2/TB))[setpts-6];[setpts-6]fps=fps=25.0[fps-3];[fps-3]trim=start=0:end=2[trim-6];nullsrc=s=480x270:d=1.0:r=25.0[nullsrc-3];[nullsrc-3][split-11]overlay=x=0:y=0:shortest=0:format=auto[overlay-3];[overlay-3]trim=start=1.0:end=1.0[trim-7];[trim-7]setpts=PTS-STARTPTS[setpts-7];[trim-6][split-10][setpts-7]concat=n=3[concat-4];[concat-4]settb=0.04[settb-3];[settb-2][settb-3]xfade=transition=fade:duration=1:offset=10.0[xfade-1];[xfade-1]split=3[split-12][split-13][split-14];[split-12]setpts=if(eq(N\,0)\,PTS-STARTPTS\,PTS-STARTPTS+(0/TB))[setpts-8];[setpts-8]fps=fps=25.0[fps-4];[fps-4]trim=start=0:end=0[trim-8];nullsrc=s=480x270:d=15.0:r=25.0[nullsrc-4];[nullsrc-4][split-14]overlay=x=0:y=0:shortest=0:format=auto[overlay-4];[overlay-4]trim=start=13.0:end=15.0[trim-9];[trim-9]setpts=PTS-STARTPTS[setpts-9];[trim-8][split-13][setpts-9]concat=n=3[concat-5];[concat-5]settb=0.04[settb-4];[img-fps-1]split=3[split-15][split-16][split-17];[split-15]setpts=if(eq(N\,0)\,PTS-STARTPTS\,PTS-STARTPTS+(2/TB))[setpts-10];[setpts-10]fps=fps=25.0[fps-5];[fps-5]trim=start=0:end=2[trim-10];nullsrc=s=480x270:d=5.0:r=25.0[nullsrc-5];[nullsrc-5][split-17]overlay=x=0:y=0:shortest=0:format=auto[overlay-5];[overlay-5]trim=start=5.0:end=5.0[trim-11];[trim-11]setpts=PTS-STARTPTS[setpts-11];[trim-10][split-16][setpts-11]concat=n=3[concat-6];[concat-6]settb=0.04[settb-5];[settb-4][settb-5]xfade=transition=fade:duration=1:offset=14.0[xfade-2]" -pix_fmt yuv420p -crf 18 -map [xfade-2] examples/concat.mp4`

This output does not depend on Docker anymore, indicating that you can let a Docker-based Veddy to export a command line, and (re-)use it to do what you want. For example, calling this command line from Python should be a simple matter. Please be minded that you need a latest version of ffmpeg installed to run this command.

Let me know if you need further assistance.

**Comment by krishyadav007** [comment]
Thanks for replying,
> heavily depends on an external program ffmpeg

Okay, but we want to access it programmatically i.e the XML will be generated by code, and then we want the video to be generated based on that XML. How will we do that?

**Comment by ryichando** [comment]
How about first writing the XML as a plain text file and call Veddy via system call (i.e., os.system() ) from your Python code?

**Comment by krishyadav007** [comment]
Will I be able to do so with docker?

**Comment by ryichando** [comment]
Assuming that you are running your program outside Docker - if you can run docker command (e.g., docker run) from your Python script; yes, you can. If not (e.g., requires admin privileges), no. Which is your case?
